name: kanban_board
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  cupertino_icons: ^1.0.6
  flutter_boardview: ^0.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  bloc_test: ^9.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
